ActiveWidgets = [
//  'wikiedits',
//  'access-index',
//  'kaspersky',
//  'tor-clients',
//  'akamaitraffic',
//  'broadband-cost',
//  'akamaiattacks',
//  'change-org',
//  'mediacloud-topics',
//  'herdict',
//  'mediacloud-stories',
//  'global-voices',
//  'lumen',
//  'wikivolume',
//  'percent-online',
//  'percent-on-broadband',
//  'akamaitraffic2',
//  'connection-speed',
//  'user-content',
//  'embed',
//  'feed',
  'gsma-total',
  'gsma-prepaid',
  'gsma-3g',
  'gsma-4g',
  //'perma'
];
 //wikiedits access-index kaspersky tor-clients akamaitraffic broadband-cost akamaiattacks change-org mediacloud-topics herdict mediacloud-stories global-voices lumen wikivolume percent-online percent-on-broadband akamaitraffic2 connection-speed user-content embed feed
