ActiveWidgets = [
  'wikiedits',
  'wikivolume',
  'access-index',
  'percent-online',
  'connection-speed',
  'broadband-cost',
  'tor-clients',
  'akamaiattacks',
  'akamaitraffic',
  'akamaitraffic2',
  'mediacloud',
  'lumen',
  'herdict',
  'kaspersky',
  'user-content',
  'embed',
  'feed'
];
